name: Weekly Run

on:
  schedule:
    # Runs at 00:00 every Monday
    - cron: "0 0 * * 1"

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Request
        run: curl -sS https://imri29.github.io/mpscraper/discount
